; Bazookarrots, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Bazookarrots_Start
Bazookarrots_StartDisarkGenerateExternalLabel

Bazookarrots_DisarkByteRegionStart0
	db "AT20"
Bazookarrots_DisarkPointerRegionStart1
	dw Bazookarrots_ArpeggioTable	; The address of the Arpeggio table.
	dw Bazookarrots_PitchTable	; The address of the Pitch table.
	dw Bazookarrots_InstrumentTable	; The address of the Instrument table.
	dw Bazookarrots_EffectBlockTable	; The address of the Effect Block table.
Bazookarrots_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Bazookarrots_DisarkPointerRegionStart2
	dw Bazookarrots_Subsong0_Start
Bazookarrots_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Bazookarrots_ArpeggioTable
Bazookarrots_DisarkPointerRegionStart3
Bazookarrots_DisarkPointerRegionEnd3

; Declares all the Pitches.
Bazookarrots_PitchTable
Bazookarrots_DisarkPointerRegionStart4
Bazookarrots_DisarkPointerRegionEnd4

; Declares all the Instruments.
Bazookarrots_InstrumentTable
Bazookarrots_DisarkPointerRegionStart5
	dw Bazookarrots_EmptyInstrument
	dw Bazookarrots_Instrument1
	dw Bazookarrots_Instrument2
	dw Bazookarrots_Instrument3
Bazookarrots_DisarkPointerRegionEnd5

Bazookarrots_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Bazookarrots_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Bazookarrots_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Bazookarrots_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 600	; Pitch.

	db 6	; Loop to silence.

Bazookarrots_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Bazookarrots_EffectBlockTable

Bazookarrots_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Bazookarrots_Subsong0_DisarkByteRegionStart0
Bazookarrots_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 1	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 16	; Base note index (>=0).

Bazookarrots_Subsong0_Linker
Bazookarrots_Subsong0_DisarkPointerRegionStart1
; Position 0
Bazookarrots_Subsong0_Linker_Loop
	dw Bazookarrots_Subsong0_Track0
	dw Bazookarrots_Subsong0_Track1
	dw Bazookarrots_Subsong0_Track2
	dw Bazookarrots_Subsong0_LinkerBlock0

; Position 1
	dw Bazookarrots_Subsong0_Track3
	dw Bazookarrots_Subsong0_Track4
	dw Bazookarrots_Subsong0_Track2
	dw Bazookarrots_Subsong0_LinkerBlock0

Bazookarrots_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Bazookarrots_Subsong0_DisarkWordForceReference2
	dw Bazookarrots_Subsong0_Linker_Loop

Bazookarrots_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Bazookarrots_Subsong0_DisarkWordForceReference3
	dw Bazookarrots_Subsong0_SpeedTrack0	; SpeedTrack address.
Bazookarrots_Subsong0_DisarkWordForceReference4
	dw Bazookarrots_Subsong0_EventTrack0	; EventTrack address.

Bazookarrots_Subsong0_Track0
	db 167
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 60	; Waits for 1 line.

	db 44
	db 49
	db 53
	db 44
	db 49
	db 53
	db 44
	db 49
	db 53
	db 61, 6	; Waits for 7 lines.

	db 37
	db 43
	db 46
	db 37
	db 43
	db 46
	db 37
	db 43
	db 46
	db 37
	db 43
	db 46
	db 37
	db 43
	db 46
	db 60	; Waits for 1 line.

	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 61, 127	; Waits for 128 lines.


Bazookarrots_Subsong0_Track1
	db 131
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 8
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 5
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 10
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 12
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 8
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 8
	db 61, 127	; Waits for 128 lines.


Bazookarrots_Subsong0_Track2
	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 177
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 141
	db 2	; New Instrument (2).
	db 177
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 141
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Bazookarrots_Subsong0_Track3
	db 167
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 41
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 44
	db 48
	db 51
	db 44
	db 48
	db 51
	db 44
	db 48
	db 45
	db 48
	db 51
	db 45
	db 48
	db 51
	db 45
	db 48
	db 46
	db 49
	db 53
	db 46
	db 49
	db 53
	db 46
	db 49
	db 53
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 51
	db 46
	db 43
	db 51
	db 49
	db 46
	db 43
	db 49
	db 48
	db 43
	db 39
	db 48
	db 46
	db 43
	db 39
	db 46
	db 44
	db 60	; Waits for 1 line.

	db 44
	db 44
	db 44
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 44
	db 61, 127	; Waits for 128 lines.


Bazookarrots_Subsong0_Track4
	db 131
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 8
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 10
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 13
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 17
	db 60	; Waits for 1 line.

	db 15
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 10
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 8
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 15
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 20
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Bazookarrots_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Bazookarrots_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Bazookarrots_Subsong0_DisarkByteRegionEnd0
