; RabbitDies, AKG format, v1.0.

; Generated by Arkos Tracker 2.

RabbitDies_Start
RabbitDies_StartDisarkGenerateExternalLabel

RabbitDies_DisarkByteRegionStart0
	db "AT20"
RabbitDies_DisarkPointerRegionStart1
	dw RabbitDies_ArpeggioTable	; The address of the Arpeggio table.
	dw RabbitDies_PitchTable	; The address of the Pitch table.
	dw RabbitDies_InstrumentTable	; The address of the Instrument table.
	dw RabbitDies_EffectBlockTable	; The address of the Effect Block table.
RabbitDies_DisarkPointerRegionEnd1


; The addresses of each Subsong:
RabbitDies_DisarkPointerRegionStart2
	dw RabbitDies_Subsong0_Start
RabbitDies_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
RabbitDies_ArpeggioTable
RabbitDies_DisarkPointerRegionStart3
RabbitDies_DisarkPointerRegionEnd3

; Declares all the Pitches.
RabbitDies_PitchTable
RabbitDies_DisarkPointerRegionStart4
RabbitDies_DisarkPointerRegionEnd4

; Declares all the Instruments.
RabbitDies_InstrumentTable
RabbitDies_DisarkPointerRegionStart5
	dw RabbitDies_EmptyInstrument
	dw RabbitDies_Instrument1
	dw RabbitDies_Instrument2
	dw RabbitDies_Instrument3
RabbitDies_DisarkPointerRegionEnd5

RabbitDies_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
RabbitDies_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

RabbitDies_Instrument1
	db 3	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

RabbitDies_Instrument2
	db 1	; The speed (>0, 0 for 256).
RabbitDies_Instrument2_Loop	db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
RabbitDies_DisarkWordForceReference6
	dw RabbitDies_Instrument2_Loop	; Loop here.

RabbitDies_Instrument3
	db 1	; The speed (>0, 0 for 256).
RabbitDies_Instrument3_Loop	db 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
RabbitDies_DisarkWordForceReference7
	dw RabbitDies_Instrument3_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
RabbitDies_EffectBlockTable
RabbitDies_DisarkPointerRegionStart8
	dw RabbitDies_EffectBlock_P26P64P0	; Index 0
	dw RabbitDies_EffectBlock_P26P96P0	; Index 1
RabbitDies_DisarkPointerRegionEnd8

RabbitDies_EffectBlock_P26P64P0
	db 26, 64, 0
RabbitDies_EffectBlock_P26P96P0
	db 26, 96, 0

RabbitDies_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
RabbitDies_Subsong0_DisarkByteRegionStart0
RabbitDies_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 29	; Base note index (>=0).

RabbitDies_Subsong0_Linker
RabbitDies_Subsong0_DisarkPointerRegionStart1
; Position 0
RabbitDies_Subsong0_Linker_Loop
	dw RabbitDies_Subsong0_Track0
	dw RabbitDies_Subsong0_Track1
	dw RabbitDies_Subsong0_Track2
	dw RabbitDies_Subsong0_LinkerBlock0

RabbitDies_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
RabbitDies_Subsong0_DisarkWordForceReference2
	dw RabbitDies_Subsong0_Linker_Loop

RabbitDies_Subsong0_LinkerBlock0
	db 5	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
RabbitDies_Subsong0_DisarkWordForceReference3
	dw RabbitDies_Subsong0_SpeedTrack0	; SpeedTrack address.
RabbitDies_Subsong0_DisarkWordForceReference4
	dw RabbitDies_Subsong0_EventTrack0	; EventTrack address.

RabbitDies_Subsong0_Track0
	db 183
	db 2	; New Instrument (2).
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


RabbitDies_Subsong0_Track1
	db 135
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


RabbitDies_Subsong0_Track2
	db 191
	db 113	; Escape note (113).
	db 3	; New Instrument (3).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
RabbitDies_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
RabbitDies_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

RabbitDies_Subsong0_DisarkByteRegionEnd0
